### ISSUE TITLE
Gets much more item than it should

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#10]
No idea where it gets the items from.
https://my.apify.com/view/runs/QfTk7TP3jnrrwfHU2

**Comment by dtrungtin** [comment]
The total of items has been changed. Now it's 4169 items. Not sure at time you test whether the total is?

**Comment by dtrungtin** [comment]
Update SDK. Log pagination text "1-50 of 4,530 titles.".
https://github.com/dtrungtin/actor-imdb-scraper/commit/ba5a5231678e1bdb5882f4a5b34478ad056da0a9

**Comment by zpelechova** [comment]
Still: https://my.apify.com/view/runs/su3ZGhpwEy4SfgA62 **(5840)** vs https://www.imdb.com/search/title/?release_date=2021-01-01,&user_rating=8.0, **(5171)**

**Comment by dtrungtin** [comment]
It's up to the location (proxy) so it won't happen if the same IP during crawling all the pages.
From my location, I just see 1-50 of 447 titles.

Solutions:
+ Use the proxy with one IP.
+ Run without proxy.

**Comment by zpelechova** [comment]
There is difference between 
https://my.apify.com/view/runs/su3ZGhpwEy4SfgA62 (5840) vs https://www.imdb.com/search/title/?release_date=2021-01-01,&user_rating=8.0,
https://my.apify.com/view/runs/su3ZGhpwEy4SfgA62 (5840) vs https://www.imdb.com/search/title/?release_date=2021-01-01,&user_rating=8.0
(the comma in the end, for some reason imdb returns different no of results for those two.

**Comment by zpelechova** [comment]
Here it say 1 of 477 but get 586 results... https://my.apify.com/view/runs/kGJrsR5JxhY4ICeDI

**Comment by zpelechova** [comment]
07/21 fixed
