### ISSUE TITLE
Year correctly only at feature films (taken as a number from title! )

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#12]

**Comment by dtrungtin** [comment]
I don't think it's a bug. Now only taken from title.

**Comment by zpelechova** [comment]
Yeah, but then it only works on feature film and not e.g. TV series...

**Comment by dtrungtin** [comment]
Fixed. https://github.com/dtrungtin/actor-imdb-scraper/commit/a67abf7e5c43d5d0f9b57600b06f5ea264259fe0
