### ISSUE TITLE
Doesnt get all items

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#20]
https://my.apify.com/view/runs/kGJrsR5JxhY4ICeDI
Says 466 titles at the beginning but only get 350.

**Comment by zpelechova** [comment]
And here even without any erros in the log: https://my.apify.com/view/runs/yaFUFOwu17Lr7FH03

**Comment by dtrungtin** [comment]
I would say there are some duplicated items. please check them manually.

**Comment by dtrungtin** [comment]
It seems there are duplicated items in pagination. Please manually double-check.

**Comment by zpelechova** [comment]
I checked manually and there are 531 items: https://my.apify.com/view/runs/n8MqJ1HMNCyPcujuH

**Comment by dtrungtin** [comment]
It seems you give the incorrect run ?

**Comment by zpelechova** [comment]
Sorry, here: https://my.apify.com/view/runs/jIdy3jHuFdA6W3gfv

**Comment by dtrungtin** [comment]
The input looks not correct.

**Comment by zpelechova** [comment]
What do you mean?

**Comment by dtrungtin** [comment]
It's not input of the Imdb actor

**Comment by zpelechova** [comment]
We found out that the acotr deduplicates episodes (so if you have e.g. 10 episodes from one series you only get 1 result in the dataset) Working on redesign.

**Comment by zpelechova** [comment]
Fixed 07/21.
