### ISSUE TITLE
Two different layouts?

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#22]
https://my.apify.com/view/runs/7VoMXUcZ8wPscituA
https://my.apify.com/view/runs/n8MqJ1HMNCyPcujuH
These two runs are a minute from each other and one gets the info correctly and one not (different values under different keys). It happens repeatedly and randomly.
Is there possibility IMDB has different layouts?

**Comment by dtrungtin** [comment]
Exactly. Two layouts.
