### ISSUE TITLE
incorrect ratingCount number

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#23]
It saves the no twice, so instead of 22 the result is 2222.
Also would be great to have it as data type number and also results like 260k made to 260000

**Comment by dtrungtin** [comment]
In my opinion, keep 260k because it's exact data shown in web page.
260k means ~260.000, not exact 260.000. It may be 260001 or 260002 etc.

**Comment by zpelechova** [comment]
But it messe with data types quite a lot. The way to go would be to click it and take from the detail.

**Comment by zpelechova** [comment]
I will close this one and open another one for the format.
