### ISSUE TITLE
The actor could have "find" url on the input as well (some/most users start like that)

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#8]

**Comment by dtrungtin** [comment]
Please give an example.

**Comment by zpelechova** [comment]
https://www.imdb.com/find?q=ninja&ref_=nv_sr_sm

**Comment by zpelechova** [comment]
https://www.imdb.com/find?q=queens+gambit&ref_=nv_sr_sm

**Comment by dtrungtin** [comment]
The search results contain Titles, Names, Keywords, Companies, etc. so the user wants to crawl ony Titles ?

**Comment by zpelechova** [comment]
I would go with titles first.
It would be nice to have a possibility to chose between titles and keywords later on.

**Comment by zpelechova** [comment]
Great, thanks!
